name: PR Labels

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  java:
    name: Java/Maven
    runs-on: ubuntu-latest
    steps:
      - name: The Label
        run: |
          cat <<!
          ${{ toJson(github.event.label) }}
          ! | jq
      - name: PR
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request.head.sha) }}
          ! | jq
      - name: Total
        run: |
          cat <<!
          ${{ toJson(github.event) }}
          ! | jq
