name: PR Labels

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  java:
    name: Java/Maven
    runs-on: ubuntu-latest
    steps:
      - name: Labels
        run: |
          echo "${{ github.event.pull_request.labels }}" | jq
      - name: Full
        run: |
          echo "${{ github.event.pull_request }}" | jq
