name: PR Labels

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  java:
    name: Java/Maven
    runs-on: ubuntu-latest
    steps:
      - name: Labels
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request.labels) }}
          ! | jq
      - name: Full
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request) }}
          ! | jq
      - name: Total
        run: |
          cat <<!
          ${{ toJson(github.event) }}
          ! | jq
