name: PR Dummy-CI

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  java:
    name: Java/Maven PR
    if: (github.event.action != 'labeled' && github.event.action != 'labeled') || startsWith(github.event.label.name, 'pr-')
    runs-on: ubuntu-latest
    steps:
      - name: Action
        run: |
          echo "event-action: ${{github.event.action}}"
      - name: Hello
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request.labels) }}
          ! | jq
      - name: World
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request) }}
          ! | jq
      - name: Universe
        run: |
          cat <<!
          ${{ toJson(github.event) }}
          ! | jq
