name: PR Dummy-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  java:
    name: Java/Maven PR
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request.labels) }}
          ! | jq
      - name: World
        run: |
          cat <<!
          ${{ toJson(github.event.pull_request) }}
          ! | jq
      - name: Universe
        run: |
          cat <<!
          ${{ toJson(github.event) }}
          ! | jq
